DROP TABLE IF EXISTS diary;

CREATE TABLE diary (
    id INT GENERATED ALWAYS AS IDENTITY,
    date DATE DEFAULT NOW(),
    time TIME DEFAULT NOW(),
    category VARCHAR (30) NOT NULL,
    text VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);


 